Add missing override to ~GeneratedExtensionFinder()
Fixes a warning with -Weverything:
src/google/protobuf/extension_set.h:153:11: error: '~GeneratedExtensionFinder' overrides a destructor but is not marked 'override' [-Werror,-Winconsistent-missing-destructor-override]

Bug: 117607748
Test: m checkbuild
Change-Id: Ie799eb95b5134aa957cc8a5010e7382aa94f9ba8